// Статические данные для приложения "Ярик.Уроки"

// Слова для чтения с фонетической транскрипцией
const syllablesLevel1 = [
    {word: "КА-ША", transcription: "[ка'ша]"},
    {word: "НЕ-БО", transcription: "[н'э'бо]"},
    {word: "РЫ-БА", transcription: "[ры'ба]"},
    {word: "РУ-КА", transcription: "[ру'ка]"},
    {word: "БЕ-ДА", transcription: "[б'и'да]"},
    {word: "ВО-ДА", transcription: "[во'да]"},
    {word: "ГУ-СИ", transcription: "[гу'с'и]"},
    {word: "ДЕ-ЛО", transcription: "[д'э'ло]"},
    {word: "ЖЕ-ЛЕ", transcription: "[жы'л'э]"},
    {word: "ЗИ-МА", transcription: "[з'и'ма]"},
    {word: "КУ-РЫ", transcription: "[ку'ры]"},
    {word: "ЛЕ-ТО", transcription: "[л'э'то]"},
    {word: "МУ-ХА", transcription: "[му'ха]"},
    {word: "НО-РА", transcription: "[но'ра]"},
    {word: "ПЕ-НА", transcription: "[п'э'на]"},
    {word: "РА-МА", transcription: "[ра'ма]"},
    {word: "СА-ЛО", transcription: "[са'ло]"},
    {word: "ЦЕ-НА", transcription: "[цэ'на]"},
    {word: "ЩУ-КА", transcription: "[щу'ка]"},
    {word: "ЛА-ПА", transcription: "[ла'па]"},
    {word: "КО-ЗА", transcription: "[ко'за]"},
    {word: "ВЕ-СЫ", transcription: "[в'э'сы]"},
    {word: "ГУ-БА", transcription: "[гу'ба]"},
    {word: "МО-РЕ", transcription: "[мо'р'и]"},
    {word: "МА-МА", transcription: "[ма'ма]"},
    {word: "ПА-ПА", transcription: "[па'па]"},
    {word: "ЧУ-ДО", transcription: "[чу'да]"},
    {word: "ПО-ЛЕ", transcription: "[по'л'и]"},
    {word: "ПИ-ЛА", transcription: "[п'и'ла]"},
    {word: "ЛУ-ЖА", transcription: "[лу'жа]"},
    {word: "ЛУ-ЧИ", transcription: "[лу'чи]"},
    {word: "НО-ГИ", transcription: "[но'г'и]"},
    {word: "РЕ-КА", transcription: "[р'и'ка]"},
    {word: "КИ-НО", transcription: "[к'и'но]"},
    {word: "ЗА-РЯ", transcription: "[за'р'я]"},
    {word: "ЖА-РА", transcription: "[жа'ра]"},
    {word: "ГО-РА", transcription: "[го'ра]"},
    {word: "ШУ-БА", transcription: "[шу'ба]"},
    {word: "ША-РЫ", transcription: "[ша'ры]"},
    {word: "ЧА-СЫ", transcription: "[ча'сы]"},
    {word: "БУ-СЫ", transcription: "[бу'сы]"},
    {word: "РО-ЗА", transcription: "[ро'за]"},
    {word: "ЖА-БА", transcription: "[жа'ба]"},
    {word: "ЛЫ-ЖИ", transcription: "[лы'жи]"},
    {word: "БУ-РЯ", transcription: "[бу'р'я]"},
    {word: "СИ-ЛА", transcription: "[с'и'ла]"},
    {word: "ВА-ТА", transcription: "[ва'та]"},
    {word: "ЛИ-СА", transcription: "[л'и'са]"},
    {word: "ВА-ЗА", transcription: "[ва'за]"},
    {word: "СО-ВА", transcription: "[со'ва]"}
];

const syllablesLevel2 = [
    {word: "КОТ", transcription: "[кот]"},
    {word: "ДОМ", transcription: "[дом]"},
    {word: "СОК", transcription: "[сок]"},
    {word: "НОС", transcription: "[нос]"},
    {word: "РОТ", transcription: "[рот]"},
    {word: "МАК", transcription: "[мак]"},
    {word: "РАК", transcription: "[рак]"},
    {word: "БАК", transcription: "[бак]"},
    {word: "ЛАК", transcription: "[лак]"},
    {word: "СЫН", transcription: "[сын]"},
    {word: "ДЕН", transcription: "[д'эн]"},
    {word: "ЛЕС", transcription: "[л'эс]"},
    {word: "ПЁС", transcription: "[п'ёс]"},
    {word: "ВЕС", transcription: "[в'эс]"},
    {word: "МЁД", transcription: "[м'ёд]"},
    {word: "ХЛЕБ", transcription: "[хл'эп]"},
    {word: "ЛЁД", transcription: "[л'ёд]"},
    {word: "ГНОМ", transcription: "[гном]"},
    {word: "СНЕГ", transcription: "[сн'эк]"},
    {word: "СТОЛ", transcription: "[стол]"},
    {word: "СТУЛ", transcription: "[стул]"},
    {word: "МОСТ", transcription: "[мост]"},
    {word: "ЛИСТ", transcription: "[л'ист]"},
    {word: "ЦВЕТ", transcription: "[цв'эт]"},
    {word: "БРАТ", transcription: "[брат]"},
    {word: "СЕСТ", transcription: "[с'эст]"},
    {word: "ДРУГ", transcription: "[друг]"},
    {word: "ВРАГ", transcription: "[враг]"},
    {word: "ШАР", transcription: "[шар]"},
    {word: "МЯЧ", transcription: "[м'яч]"},
    {word: "НОЖ", transcription: "[нож]"},
    {word: "МЕЧ", transcription: "[м'эч]"},
    {word: "ДУБ", transcription: "[дуб]"},
    {word: "ЁЖ", transcription: "[ёж]"},
    {word: "УЖ", transcription: "[уж]"},
    {word: "УХО", transcription: "[у'хо]"},
    {word: "ОКО", transcription: "[о'ко]"},
    {word: "НОГА", transcription: "[но'га]"},
    {word: "РУКА", transcription: "[ру'ка]"},
    {word: "ЩЕКА", transcription: "[щэ'ка]"},
    {word: "ПОЛ", transcription: "[пол]"},
    {word: "ПОТ", transcription: "[пот]"},
    {word: "РОГ", transcription: "[рог]"},
    {word: "РОК", transcription: "[рок]"},
    {word: "ВОЛ", transcription: "[вол]"},
    {word: "ВОЗ", transcription: "[воз]"},
    {word: "ГАЗ", transcription: "[газ]"},
    {word: "ГУБ", transcription: "[гуп]"},
    {word: "ЗУБ", transcription: "[зуп]"},
    {word: "ЛУК", transcription: "[лук]"}
];

const syllablesLevel3 = [
    {word: "КО-РО-ВА", transcription: "[ко'ро'ва]"},
    {word: "МО-ЛО-КО", transcription: "[мо'ло'ко]"},
    {word: "СО-БА-КА", transcription: "[со'ба'ка]"},
    {word: "ЛО-ША-ДЬ", transcription: "[ло'шад']"},
    {word: "КУ-РИ-ЦА", transcription: "[ку'р'и'ца]"},
    {word: "МА-ШИ-НА", transcription: "[ма'шы'на]"},
    {word: "РА-КЕ-ТА", transcription: "[ра'к'э'та]"},
    {word: "СА-МО-ЛЁТ", transcription: "[са'ма'л'ёт]"},
    {word: "ВЕ-ЛО-СИП", transcription: "[в'э'ла'с'ип]"},
    {word: "ТЕ-ЛЕ-ФОН", transcription: "[т'э'л'э'фон]"},
    {word: "О-КЕ-АН", transcription: "[а'к'э'ан]"},
    {word: "Я-ГО-ДА", transcription: "[я'го'да]"},
    {word: "МА-ЛИ-НА", transcription: "[ма'л'и'на]"},
    {word: "ПО-МИ-ДОР", transcription: "[по'м'и'дор]"},
    {word: "О-ГУ-РЕЦ", transcription: "[а'гу'р'эц]"},
    {word: "КА-ПУ-СТА", transcription: "[ка'пу'ста]"},
    {word: "МОР-КОВЬ", transcription: "[мор'коф']"},
    {word: "ПА-НА-МА", transcription: "[па'на'ма]"},
    {word: "ПИ-ДЖАК", transcription: "[п'и'джак]"},
    {word: "СА-ПО-ГИ", transcription: "[са'по'г'и]"},
    {word: "БО-ТИН-КИ", transcription: "[ба'т'ин'к'и]"},
    {word: "ПА-ЛЬ-ТО", transcription: "[па'л'то]"},
    {word: "ША-ПКА", transcription: "[ша'пка]"},
    {word: "ШАР-ФИК", transcription: "[шар'ф'ик]"},
    {word: "ВО-РО-ТА", transcription: "[во'ро'та]"},
    {word: "О-КНО", transcription: "[а'кно]"},
    {word: "ПО-ЛЕ", transcription: "[по'л'и]"},
    {word: "РЕ-КА", transcription: "[р'э'ка]"},
    {word: "МО-РЕ", transcription: "[мо'р'и]"},
    {word: "ГО-РА", transcription: "[го'ра]"}
];

// Реплики для правильных ответов
const correctResponses = [
    "Хорошая работа, Ярослав! Правильно!",
    "Ты самый умный, Ярослав! Так держать!",
    "Верно, Ярик! Ты умница!",
    "Правильно, Ярослав! Супер!",
    "Замечательно, Ярик! Ты справился!"
];

// Реплики для неправильных ответов
const wrongResponses = [
    "Ничего, Ярик, в следующий раз получится!",
    "Не расстраивайся, Ярослав, попробуй ещё раз!",
    "Ошибиться может каждый, Ярик, главное — не сдаваться!",
    "Ну, Ярослав, ничего страшного, подумай ещё!",
    "Попробуй ответить правильно, Ярик!"
];

// Описания слов для демонстрации
const wordDescriptions = {
    'КАША': 'вкусная, горячая, молочная, рассыпчатая',
    'НЕБО': 'голубое, высокое, облачное, ясное',
    'РЫБА': 'речная, морская, золотая, живая',
    'РУКА': 'сильная, теплая, правая, левая',
    'ВОДА': 'чистая, холодная, питьевая, прозрачная',
    'МАМА': 'любимая, добрая, заботливая, родная',
    'ПАПА': 'сильный, добрый, умный, любимый',
    'КОТ': 'пушистый, мягкий, домашний, игривый',
    'ДОМ': 'уютный, теплый, родной, большой',
    'ЛЕС': 'густой, зеленый, хвойный, дремучий',
    'ПЕНА': 'белая, воздушная, мягкая, пушистая',
    'СОБАКА': 'верный, дружелюбный, умный, домашний',
    'МАШИНА': 'быстрая, современная, удобная, личная',
    'ЯГОДА': 'сладкая, спелая, сочная, лесная',
    'МОРЕ': 'глубокое, синее, теплое, соленое'
};

// Имена уровней сложности
const levelNames = {
    1: 'Легкий',
    2: 'Средний',
    3: 'Сложный',
    4: 'Математика'
};
